name: Dispatch Token Request

on:
  issues:
    types: [opened]

jobs:
  fetch-opened-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Opened Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number=${{ github.event.issue.number }}
          issue_body="${{ github.event.issue.body }}"
          issue_author="${{ github.event.issue.user.id }}"

          issue_json=$(jq -n \
            --arg number "$issue_number" \
            --arg body "$issue_body" \
            --arg author "$issue_author" \
            '{number: $number, body: $body, author: $author}')

          echo "$issue_json" > opened_issue.json
          echo "Fetched issue details: $issue_json"

      - name: Process Request
        run: |
          echo "Will do something here... gimme a minute"

      - name: Close the Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number=${{ github.event.issue.number }}
          gh issue close "$issue_number" --reason "completed"
          echo "Closed issue #$issue_number"
